CREATE TABLE agendamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_hora_inicio TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    data_hora_fim TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    status VARCHAR(20) NOT NULL,
    observacao VARCHAR(1000),
    data_criacao TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    ordem_servico_id BIGINT NOT NULL,
    tecnico_id BIGINT NOT NULL,
    empresa_id BIGINT NOT NULL,
    CONSTRAINT agendamento_status_check
        CHECK (status IN ('AGENDADO', 'CONFIRMADO', 'EM_ATENDIMENTO', 'CONCLUIDO', 'CANCELADO')),
    CONSTRAINT fk_agendamento_ordem_servico
        FOREIGN KEY (ordem_servico_id) REFERENCES ordem_servico(id),
    CONSTRAINT fk_agendamento_tecnico
        FOREIGN KEY (tecnico_id) REFERENCES usuario(id),
    CONSTRAINT fk_agendamento_empresa
        FOREIGN KEY (empresa_id) REFERENCES empresa(id)
);

CREATE INDEX idx_agendamento_empresa_id
    ON agendamento(empresa_id);

CREATE INDEX idx_agendamento_tecnico_id
    ON agendamento(tecnico_id);

CREATE INDEX idx_agendamento_ordem_servico_id
    ON agendamento(ordem_servico_id);

CREATE INDEX idx_agendamento_data_hora_inicio
    ON agendamento(data_hora_inicio);

CREATE TABLE agendamento_historico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_alteracao TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    status_anterior VARCHAR(20),
    status_novo VARCHAR(20) NOT NULL,
    agendamento_id BIGINT NOT NULL,
    usuario_id BIGINT,
    CONSTRAINT agendamento_historico_status_anterior_check
        CHECK (status_anterior IS NULL OR status_anterior IN ('AGENDADO', 'CONFIRMADO', 'EM_ATENDIMENTO', 'CONCLUIDO', 'CANCELADO')),
    CONSTRAINT agendamento_historico_status_novo_check
        CHECK (status_novo IN ('AGENDADO', 'CONFIRMADO', 'EM_ATENDIMENTO', 'CONCLUIDO', 'CANCELADO')),
    CONSTRAINT fk_agendamento_historico_agendamento
        FOREIGN KEY (agendamento_id) REFERENCES agendamento(id),
    CONSTRAINT fk_agendamento_historico_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);
