CREATE TABLE plano_manutencao_preventiva (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    intervalo_meses INTEGER NOT NULL,
    proxima_execucao DATE NOT NULL,
    ultima_execucao DATE,
    ativo BOOLEAN NOT NULL,
    observacao VARCHAR(1000),
    data_criacao TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    equipamento_id BIGINT NOT NULL,
    tecnico_padrao_id BIGINT,
    empresa_id BIGINT NOT NULL,
    CONSTRAINT plano_manutencao_preventiva_intervalo_meses_check
        CHECK (intervalo_meses > 0),
    CONSTRAINT fk_plano_manutencao_preventiva_equipamento
        FOREIGN KEY (equipamento_id) REFERENCES equipamento(id),
    CONSTRAINT fk_plano_manutencao_preventiva_tecnico_padrao
        FOREIGN KEY (tecnico_padrao_id) REFERENCES usuario(id),
    CONSTRAINT fk_plano_manutencao_preventiva_empresa
        FOREIGN KEY (empresa_id) REFERENCES empresa(id)
);

CREATE INDEX idx_plano_manutencao_preventiva_empresa_id
    ON plano_manutencao_preventiva(empresa_id);

CREATE INDEX idx_plano_manutencao_preventiva_equipamento_id
    ON plano_manutencao_preventiva(equipamento_id);

CREATE INDEX idx_plano_manutencao_preventiva_proxima_execucao
    ON plano_manutencao_preventiva(proxima_execucao);

CREATE INDEX idx_plano_manutencao_preventiva_ativo
    ON plano_manutencao_preventiva(ativo);

CREATE TABLE plano_manutencao_preventiva_execucao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_referencia DATE NOT NULL,
    data_execucao TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    plano_manutencao_preventiva_id BIGINT NOT NULL,
    ordem_servico_id BIGINT NOT NULL,
    usuario_id BIGINT,
    CONSTRAINT fk_plano_manutencao_preventiva_execucao_plano
        FOREIGN KEY (plano_manutencao_preventiva_id) REFERENCES plano_manutencao_preventiva(id),
    CONSTRAINT fk_plano_manutencao_preventiva_execucao_ordem_servico
        FOREIGN KEY (ordem_servico_id) REFERENCES ordem_servico(id),
    CONSTRAINT fk_plano_manutencao_preventiva_execucao_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuario(id),
    CONSTRAINT uq_plano_manutencao_preventiva_execucao_ocorrencia
        UNIQUE (plano_manutencao_preventiva_id, data_referencia)
);

CREATE INDEX idx_plano_manutencao_preventiva_execucao_plano_id
    ON plano_manutencao_preventiva_execucao(plano_manutencao_preventiva_id);
