ALTER TABLE empresa
    ADD COLUMN logradouro VARCHAR(150),
    ADD COLUMN numero VARCHAR(20),
    ADD COLUMN complemento VARCHAR(100),
    ADD COLUMN bairro VARCHAR(100),
    ADD COLUMN cidade VARCHAR(100),
    ADD COLUMN uf VARCHAR(2),
    ADD COLUMN cep VARCHAR(10),
    ADD COLUMN inscricao_municipal VARCHAR(30),
    ADD COLUMN regime_tributario VARCHAR(30),
    ADD COLUMN codigo_servico_padrao VARCHAR(20),
    ADD COLUMN aliquota_iss_padrao NUMERIC(5, 2);

ALTER TABLE empresa
    ADD CONSTRAINT empresa_regime_tributario_check
        CHECK (regime_tributario IS NULL OR regime_tributario IN ('SIMPLES_NACIONAL', 'LUCRO_PRESUMIDO', 'LUCRO_REAL', 'MEI'));

ALTER TABLE cliente
    ADD COLUMN logradouro VARCHAR(150),
    ADD COLUMN numero VARCHAR(20),
    ADD COLUMN complemento VARCHAR(100),
    ADD COLUMN bairro VARCHAR(100),
    ADD COLUMN cidade VARCHAR(100),
    ADD COLUMN uf VARCHAR(2),
    ADD COLUMN cep VARCHAR(10),
    ADD COLUMN inscricao_municipal VARCHAR(30),
    ADD COLUMN inscricao_estadual VARCHAR(30);

CREATE TABLE nota_fiscal_servico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(20) NOT NULL,
    ambiente VARCHAR(20) NOT NULL,
    discriminacao_servico VARCHAR(1000) NOT NULL,
    codigo_servico VARCHAR(20),
    aliquota_iss NUMERIC(5, 2),
    valor_servico NUMERIC(12, 2) NOT NULL,
    valor_iss NUMERIC(12, 2),
    numero_nota VARCHAR(30),
    codigo_verificacao VARCHAR(50),
    motivo_rejeicao VARCHAR(1000),
    data_emissao TIMESTAMP(6) WITHOUT TIME ZONE,
    payload_montado TEXT,
    data_criacao TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    ordem_servico_id BIGINT NOT NULL,
    orcamento_id BIGINT NOT NULL,
    empresa_id BIGINT NOT NULL,
    CONSTRAINT nota_fiscal_servico_status_check
        CHECK (status IN ('RASCUNHO', 'ENVIADA', 'AUTORIZADA', 'REJEITADA', 'CANCELADA')),
    CONSTRAINT nota_fiscal_servico_ambiente_check
        CHECK (ambiente IN ('HOMOLOGACAO', 'PRODUCAO')),
    CONSTRAINT fk_nota_fiscal_servico_ordem_servico
        FOREIGN KEY (ordem_servico_id) REFERENCES ordem_servico(id),
    CONSTRAINT fk_nota_fiscal_servico_orcamento
        FOREIGN KEY (orcamento_id) REFERENCES orcamento(id),
    CONSTRAINT fk_nota_fiscal_servico_empresa
        FOREIGN KEY (empresa_id) REFERENCES empresa(id)
);

CREATE INDEX idx_nota_fiscal_servico_empresa_id
    ON nota_fiscal_servico(empresa_id);

CREATE INDEX idx_nota_fiscal_servico_ordem_servico_id
    ON nota_fiscal_servico(ordem_servico_id);

CREATE INDEX idx_nota_fiscal_servico_status
    ON nota_fiscal_servico(status);
