-- ClimaService initial schema
-- Baseline generated from the current PostgreSQL schema.

CREATE TABLE public.cliente (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cpf_cnpj varchar(14),
    email varchar(150),
    nome varchar(150) NOT NULL,
    telefone varchar(20)
);

CREATE TABLE public.usuario (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ativo boolean NOT NULL,
    data_criacao timestamp(6) without time zone NOT NULL,
    email varchar(150) NOT NULL,
    nome varchar(150) NOT NULL,
    role varchar(20) NOT NULL,
    senha_hash varchar(255) NOT NULL,
    CONSTRAINT uk_usuario_email UNIQUE (email),
    CONSTRAINT usuario_role_check CHECK (role IN ('ADMIN', 'TECNICO', 'ATENDENTE'))
);

CREATE TABLE public.servico (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ativo boolean NOT NULL,
    descricao varchar(500),
    nome varchar(150) NOT NULL,
    valor_padrao numeric(12,2) NOT NULL
);

CREATE TABLE public.produto (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ativo boolean NOT NULL,
    descricao varchar(500),
    nome varchar(150) NOT NULL,
    valor_padrao numeric(12,2) NOT NULL
);

CREATE TABLE public.equipamento (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    capacidade_btu integer NOT NULL,
    local_instalacao varchar(150),
    marca varchar(100) NOT NULL,
    modelo varchar(100) NOT NULL,
    numero_serie varchar(100),
    cliente_id bigint NOT NULL,
    status varchar(20),
    CONSTRAINT fk_equipamento_cliente
        FOREIGN KEY (cliente_id) REFERENCES public.cliente(id)
);

CREATE TABLE public.ordem_servico (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_abertura timestamp(6) without time zone NOT NULL,
    data_conclusao timestamp(6) without time zone,
    descricao_problema varchar(1000) NOT NULL,
    diagnostico varchar(2000),
    status varchar(30) NOT NULL,
    cliente_id bigint NOT NULL,
    equipamento_id bigint NOT NULL,
    CONSTRAINT ordem_servico_status_check
        CHECK (status IN ('ABERTA', 'EM_ANDAMENTO', 'AGUARDANDO_CLIENTE', 'CONCLUIDA', 'CANCELADA')),
    CONSTRAINT fk_ordem_servico_cliente
        FOREIGN KEY (cliente_id) REFERENCES public.cliente(id),
    CONSTRAINT fk_ordem_servico_equipamento
        FOREIGN KEY (equipamento_id) REFERENCES public.equipamento(id)
);

CREATE TABLE public.ordem_servico_historico (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_alteracao timestamp(6) without time zone NOT NULL,
    status_anterior varchar(30),
    status_novo varchar(30) NOT NULL,
    ordem_servico_id bigint NOT NULL,
    usuario_id bigint,
    CONSTRAINT ordem_servico_historico_status_anterior_check
        CHECK (status_anterior IS NULL OR status_anterior IN ('ABERTA', 'EM_ANDAMENTO', 'AGUARDANDO_CLIENTE', 'CONCLUIDA', 'CANCELADA')),
    CONSTRAINT ordem_servico_historico_status_novo_check
        CHECK (status_novo IN ('ABERTA', 'EM_ANDAMENTO', 'AGUARDANDO_CLIENTE', 'CONCLUIDA', 'CANCELADA')),
    CONSTRAINT fk_os_historico_ordem_servico
        FOREIGN KEY (ordem_servico_id) REFERENCES public.ordem_servico(id),
    CONSTRAINT fk_os_historico_usuario
        FOREIGN KEY (usuario_id) REFERENCES public.usuario(id)
);

CREATE TABLE public.ordem_servico_diagnostico_historico (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_alteracao timestamp(6) without time zone NOT NULL,
    diagnostico_anterior varchar(2000),
    diagnostico_novo varchar(2000) NOT NULL,
    ordem_servico_id bigint NOT NULL,
    usuario_id bigint,
    CONSTRAINT fk_os_diag_historico_ordem_servico
        FOREIGN KEY (ordem_servico_id) REFERENCES public.ordem_servico(id),
    CONSTRAINT fk_os_diag_historico_usuario
        FOREIGN KEY (usuario_id) REFERENCES public.usuario(id)
);

CREATE TABLE public.orcamento (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_criacao timestamp(6) without time zone NOT NULL,
    data_envio timestamp(6) without time zone,
    data_resposta timestamp(6) without time zone,
    observacao varchar(1000),
    status varchar(20) NOT NULL,
    valor_total numeric(12,2) NOT NULL,
    ordem_servico_id bigint NOT NULL,
    CONSTRAINT orcamento_status_check
        CHECK (status IN ('RASCUNHO', 'ENVIADO', 'APROVADO', 'REJEITADO', 'CANCELADO')),
    CONSTRAINT fk_orcamento_ordem_servico
        FOREIGN KEY (ordem_servico_id) REFERENCES public.ordem_servico(id)
);

CREATE TABLE public.orcamento_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao varchar(200) NOT NULL,
    quantidade integer NOT NULL,
    subtotal numeric(12,2) NOT NULL,
    tipo varchar(20) NOT NULL,
    valor_unitario numeric(12,2) NOT NULL,
    orcamento_id bigint NOT NULL,
    servico_id bigint,
    produto_id bigint,
    CONSTRAINT orcamento_item_tipo_check
        CHECK (tipo IN ('SERVICO', 'PECA')),
    CONSTRAINT fk_orcamento_item_orcamento
        FOREIGN KEY (orcamento_id) REFERENCES public.orcamento(id),
    CONSTRAINT fk_orcamento_item_servico
        FOREIGN KEY (servico_id) REFERENCES public.servico(id),
    CONSTRAINT fk_orcamento_item_produto
        FOREIGN KEY (produto_id) REFERENCES public.produto(id)
);

CREATE TABLE public.orcamento_historico (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_alteracao timestamp(6) without time zone NOT NULL,
    status_anterior varchar(20),
    status_novo varchar(20) NOT NULL,
    orcamento_id bigint NOT NULL,
    usuario_id bigint,
    CONSTRAINT orcamento_historico_status_anterior_check
        CHECK (status_anterior IS NULL OR status_anterior IN ('RASCUNHO', 'ENVIADO', 'APROVADO', 'REJEITADO', 'CANCELADO')),
    CONSTRAINT orcamento_historico_status_novo_check
        CHECK (status_novo IN ('RASCUNHO', 'ENVIADO', 'APROVADO', 'REJEITADO', 'CANCELADO')),
    CONSTRAINT fk_orcamento_historico_orcamento
        FOREIGN KEY (orcamento_id) REFERENCES public.orcamento(id),
    CONSTRAINT fk_orcamento_historico_usuario
        FOREIGN KEY (usuario_id) REFERENCES public.usuario(id)
);

CREATE TABLE public.pagamento (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_cancelamento timestamp(6) without time zone,
    data_confirmacao timestamp(6) without time zone,
    data_criacao timestamp(6) without time zone NOT NULL,
    forma_pagamento varchar(30) NOT NULL,
    observacao varchar(500),
    status varchar(20) NOT NULL,
    valor numeric(12,2) NOT NULL,
    orcamento_id bigint NOT NULL,
    CONSTRAINT pagamento_forma_pagamento_check
        CHECK (forma_pagamento IN ('DINHEIRO', 'PIX', 'CARTAO_CREDITO', 'CARTAO_DEBITO', 'BOLETO', 'TRANSFERENCIA')),
    CONSTRAINT pagamento_status_check
        CHECK (status IN ('PENDENTE', 'CONFIRMADO', 'CANCELADO')),
    CONSTRAINT fk_pagamento_orcamento
        FOREIGN KEY (orcamento_id) REFERENCES public.orcamento(id)
);

CREATE TABLE public.pagamento_historico (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_alteracao timestamp(6) without time zone NOT NULL,
    status_anterior varchar(20),
    status_novo varchar(20) NOT NULL,
    pagamento_id bigint NOT NULL,
    usuario_id bigint,
    CONSTRAINT pagamento_historico_status_anterior_check
        CHECK (status_anterior IS NULL OR status_anterior IN ('PENDENTE', 'CONFIRMADO', 'CANCELADO')),
    CONSTRAINT pagamento_historico_status_novo_check
        CHECK (status_novo IN ('PENDENTE', 'CONFIRMADO', 'CANCELADO')),
    CONSTRAINT fk_pagamento_historico_pagamento
        FOREIGN KEY (pagamento_id) REFERENCES public.pagamento(id),
    CONSTRAINT fk_pagamento_historico_usuario
        FOREIGN KEY (usuario_id) REFERENCES public.usuario(id)
);
