CREATE TABLE empresa (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         nome VARCHAR(150) NOT NULL,
                         cpf_cnpj VARCHAR(14),
                         ativo BOOLEAN NOT NULL,
                         data_criacao TIMESTAMP NOT NULL
);

INSERT INTO empresa (
    nome,
    cpf_cnpj,
    ativo,
    data_criacao
)
VALUES (
           'Empresa Inicial',
           NULL,
           TRUE,
           CURRENT_TIMESTAMP
       );

ALTER TABLE usuario
    ADD COLUMN empresa_id BIGINT;

UPDATE usuario
SET empresa_id = (
    SELECT id
    FROM empresa
    WHERE nome = 'Empresa Inicial'
    LIMIT 1
    );

ALTER TABLE usuario
    ALTER COLUMN empresa_id SET NOT NULL;

ALTER TABLE usuario
    ADD CONSTRAINT fk_usuario_empresa
        FOREIGN KEY (empresa_id)
            REFERENCES empresa(id);

CREATE INDEX idx_usuario_empresa_id
    ON usuario(empresa_id);